groups:
  - name: fleetpulse-alerts
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[2m])) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Erro 5xx alto na API"
