global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fleetpulse-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api:8080']

rule_files:
  - alert.rules.yml
