# docker-compose.yml
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet
      POSTGRES_DB: fleetpulse
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleet"]
      interval: 5s
      retries: 5

  redpanda:
    image: redpandadata/redpanda:latest
    command: >
      redpanda start --overprovisioned
                     --node-id 0
                     --kafka-addr PLAINTEXT://0.0.0.0:9092
    ports: ["9092:9092"]

  api:
    build:
      context: ./backend/api        # ← aponta para a pasta que contém o pom.xml e o Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fleetpulse
      SPRING_DATASOURCE_USERNAME: fleet
      SPRING_DATASOURCE_PASSWORD: fleet
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      NEXT_PUBLIC_API_URL: http://api:8080/api
    ports: ["8080:8080"]

  web:
    build:
      context: ./frontend
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    ports: ["3000:3000"]
