version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet
      POSTGRES_DB: fleetpulse
    ports: [ "5432:5432" ]

  kafka:
    image: redpandadata/redpanda:latest
    command: redpanda start --overprovisioned --node-id 0 --kafka-addr PLAINTEXT://0.0.0.0:9092
    ports: [ "9092:9092" ]
