name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend · Maven + JaCoCo
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: fleet
          POSTGRES_PASSWORD: fleet
          POSTGRES_DB: fleetpulse
        ports: [5432:5432]
        options: >-
          --health-cmd="pg_isready -U fleet"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: backend/api

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          cache-dependency-path: backend/api/pom.xml

      - name: Maven verify (tests + JaCoCo)
        run: mvn -B verify

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/api/target/site/jacoco/

  frontend:
    name: Frontend · Lint & Coverage
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Vitest coverage
        run: |
          npm run coverage       
          cp coverage/lcov.info ${{ github.workspace }}/frontend-lcov.info

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage/

  docker-build:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t fleetpulse-api ./backend/api

      - name: Build frontend image
        run: docker build -t fleetpulse-web ./frontend
